# Generated by Django 3.1.6 on 2021-02-06 23:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0002_auto_20210206_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='student',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='student_academy_set', to='academy.student'),
        ),
        migrations.AlterField(
            model_name='group',
            name='teacher',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='teacher_academy_set', to='academy.lecturer'),
        ),
    ]
