# Generated by Django 3.1.6 on 2021-02-06 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0004_auto_20210206_2320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='student',
        ),
        migrations.AddField(
            model_name='group',
            name='student',
            field=models.ManyToManyField(to='academy.Student'),
        ),
    ]
