# Generated by Django 3.1.6 on 2021-02-10 23:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0005_auto_20210206_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='student',
            field=models.ManyToManyField(blank=True, to='academy.Student'),
        ),
        migrations.AlterField(
            model_name='group',
            name='teacher',
            field=models.ForeignKey(
                blank=True, on_delete=django.db.models.deletion.CASCADE,
                related_name='teacher_academy_set', to='academy.lecturer'),
        ),
    ]
