# Generated by Django 3.1.6 on 2021-02-14 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0006_auto_20210210_2356'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lecturer',
            options={'ordering': ('first_name',)},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ('first_name',)},
        ),
        migrations.AlterField(
            model_name='group',
            name='student',
            field=models.ManyToManyField(to='academy.Student'),
        ),
        migrations.AlterField(
            model_name='group',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_academy_set', to='academy.lecturer'),
        ),
    ]
