# Generated by Django 3.1.6 on 2021-02-27 22:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
